language: python
python: 3.6

matrix:
  include:
    # Code Quality Checks
    - env: TOXENV=lint
    - env: TOXENV=docs
    - env: TOXENV=packaging

    # Test Suite
    - python: pypy3
    - python: pypy

    - python: 2.7
    - python: 3.7
      sudo: required
      dist: xenial

    - python: 3.6
    - python: 3.5
    - python: 3.4

    - python: 3.8-dev

  allow_failures:
    - python: 3.8-dev

install:
  - pip install --upgrade tox

before_script:
  - source ./tools/travis/tox-env.sh

script:
  - tox
