language: python
python: 3.6

matrix:
  include:
    # Code Quality Checks
    - env: KIND=lint
    - env: KIND=docs
    - env: KIND=packaging

    # Test Suite
    - python: pypy3
    - python: pypy

    - python: 2.7
    - python: 3.7
      sudo: required
      dist: xenial

    - python: 3.6
    - python: 3.5
    - python: 3.4

    - python: nightly
      env: KIND=test

  allow_failures:
    - python: nightly

install:
  - pip install --upgrade nox-automation
  - ./tools/travis/install.sh

before_script:
  - export SESSION="${KIND:-test-${TRAVIS_PYTHON_VERSION}}"
script:
  - nox -s $SESSION
